import "~/styles/globals.css";

import { Alata, Josefin_Sans } from "next/font/google";

const alata = Alata({
  variable: "--font-alata",
  weight: "400",
  subsets: ["latin"],
});

const josefin = Josefin_Sans({
  variable: "--font-josefin",
  subsets: ["latin"],
  weight: "300",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${josefin.variable} ${alata.variable}`}>
        {children}
      </body>
    </html>
  );
}
